import joy from './assets/album-joy-division.png';
import kendrick from './assets/album-kendrick-lamar.png';
import miles from './assets/album-miles-davis.png';
import tyler from './assets/album-tyler-creator.png';
import mia from './assets/album-mia.png';
import david from './assets/album-david-bowie.png';
import tame from './assets/album-tame-impala.png';
import johnny from './assets/album-johnny-cash.png';

export const albums = [
    {
        id: 'joy-division',
        idTitle: 'unknown-pleasures',
        name: "Joy Division",
        title: "Unknown Pleasures",
        background: `url(${joy})`,
        year: '1979',
        tracks: '10',
        length: '39:28',
        trackList: [
            { song: "Disorder", lyrics: ['blabla'] },
            { song: "Day of the Lords", lyrics: [] },
            { song: "Candidate", lyrics: [] },
            { song: "Insight", lyrics: [] },
            { song: "New Dawn Fades", lyrics: [] },
            { song: "She's Lost Control", lyrics: [] },
            { song: "Shadowplay", lyrics: [] },
            { song: "Wilderness", lyrics: [] },
            { song: "Interzone", lyrics: [] },
            { song: "I Remember Nothing", lyrics: [] }
        ],
    },

    {
        id: 'kendrick-lamar',
        idTitle: 'to-pimp-a-butterfly',
        name: "Kendrick Lamar",
        title: "To Pimp a Butterfly",
        background: `url(${kendrick})`,
        year: '2015',
        tracks: '16',
        length: '78:51',
        trackList: [
            { song: "Wesley's Theory (feat. George Clinton and Thundercat)", lyrics: [] },
            { song: "For Free? (Interlude)", lyrics: [] },
            { song: "King Kunta", lyrics: [] },
            { song: "Institutionalized (feat. Bilal, Anna Wise and Snoop Dogg)", lyrics: [] },
            { song: "These Walls (feat. Bilal, Anna Wise and Thundercat)", lyrics: [] },
            { song: "U", lyrics: [] },
            { song: "Alright", lyrics: [] },
            { song: "For Sale? (Interlude)", lyrics: [] },
            { song: "Momma", lyrics: [] },
            { song: "Hood Politics", lyrics: [] },
            { song: "How Much a Dollar Cost (feat. James Fauntleroy and Ronald Isley)", lyrics: [] },
            { song: "Complexion (A Zulu Love) (feat. Rapsody)", lyrics: [] },
            { song: "The Blacker the Berry", lyrics: [] },
            { song: "You Ain't Gotta Lie (Momma Said)", lyrics: [] },
            { song: "I", lyrics: [] },
            { song: "Mortal Man", lyrics: [] }
        ],
    },

    {
        id: 'miles-davis',
        idTitle: 'bitches-brew',
        name: "Miles Davis",
        title: "Bitches Brew",
        background: `url(${miles})`,
        year: '1969',
        tracks: '6',
        length: '94:11',
        trackList: [
            { song: "Pharaoh's Dance", lyrics: [] },
            { song: "Bitches Brew", lyrics: [] },
            { song: "Spanish Key", lyrics: [] },
            { song: "John McLaughlin", lyrics: [] },
            { song: "Miles Runs the Voodoo Down", lyrics: [] },
            { song: "Sanctuary", lyrics: [] },
        ],
    },

    {
        id: 'tyler-the-creator',
        idTitle: 'igor',
        name: "Tyler, The Creator",
        title: "Igor",
        background: `url(${tyler})`,
        year: '2019',
        tracks: '12',
        length: '39:43',
        trackList: [
            { song: "Igor's Theme", lyrics: [] },
            { song: "Earfquake", lyrics: [] },
            { song: "I think", lyrics: [] },
            { song: "Exactly what you run from you end up chasing", lyrics: [] },
            { song: "Running out of time", lyrics: [] },
            { song: "New magic wand", lyrics: [] },
            { song: "A boy is a gun*", lyrics: [] },
            { song: "Puppet", lyrics: [] },
            { song: "What's good", lyrics: [] },
            { song: "Gone, gone / Thank you", lyrics: [] },
            { song: "I don't love you anymore", lyrics: [] },
            { song: "Are we still friends?", lyrics: [] },
        ],
    },
    {
        id: 'mia',
        idTitle: 'kala',
        name: "Mia",
        title: "Kala",
        background: `url(${mia})`,
        year: '2007',
        tracks: '12',
        length: '47:32',
        trackList: [
            { song: "Bamboo Banga", lyrics: [] },
            { song: "Bird Flu", lyrics: [] },
            { song: "Boyz", lyrics: [] },
            { song: "Jimmy", lyrics: [] },
            { song: "Hussel (feat. Afrikan Boy)", lyrics: [] },
            { song: "Mango Pickle Down River (with The Wilcannia Mob)", lyrics: [] },
            { song: "20 Dollar", lyrics: [] },
            { song: "World Town", lyrics: [] },
            { song: "The Turn", lyrics: [] },
            { song: "XR2", lyrics: [] },
            { song: "Paper Planes", lyrics: [] },
        ],
    },
    {
        id: 'david-bowie',
        idTitle: 'aladdin-sane',
        name: "David Bowie",
        title: "Aladdin Sane",
        background: `url(${david})`,
        year: '1973',
        tracks: '10',
        length: '40:47',
        trackList: [
            { song: "Watch That Man", lyrics: [] },
            { song: "Aladdin Sane (1913–1938–197?)", lyrics: [] },
            { song: "Drive-In Saturday", lyrics: [] },
            { song: "Panic in Detroit", lyrics: [], },
            { song: "Cracked Actor", lyrics: [] },
            { song: "Time", lyrics: [] },
            { song: "The Prettiest Star", lyrics: [] },
            { song: "Let's Spend the Night Together", lyrics: [] },
            { song: "The Jean Genie", lyrics: [] },
            { song: "Lady Grinning Soul", lyrics: [] }
        ],
    },
    {
        id: 'tame-impala',
        idTitle: 'currents',
        name: "Tame Impala",
        title: "Currents",
        background: `url(${tame})`,
        year: '2015',
        tracks: '13',
        length: '51:12',
        trackList: [
            { song: "Let It Happen", lyrics: [], },
            { song: "Nangs", lyrics: [] },
            { song: "The Moment", lyrics: [] },
            { song: "Yes I'm Changing", lyrics: [] },
            { song: "Eventually", lyrics: [] },
            { song: "Gossip", lyrics: [] },
            { song: "The Less I Know the Better", lyrics: [] },
            { song: "Past Life", lyrics: [] },
            { song: "Disciples", lyrics: [] },
            { song: "'Cause I'm a Man", lyrics: [] },
            { song: "Reality in Motion", lyrics: [] },
            { song: "Love/Paranoia", lyrics: [] },
            { song: "New Person, Same Old Mistakes", lyrics: [] },
        ],
    },
    {
        id: 'johnny-cash',
        idTitle: 'american-iv-the-man-comes-around',
        name: "Johnny Cash",
        title: "American IV: The Man Comes Around",
        background: `url(${johnny})`,
        year: '2002',
        tracks: '15',
        length: '51:52',
        trackList: [
            { song: "The Man Comes Around", lyrics: [] },
            { song: "Hurt", lyrics: [] },
            { song: "Give My Love to Rose", lyrics: [] },
            { song: "Bridge Over Troubled Water (with Fiona Apple)", lyrics: [] },
            { song: "I Hung My Head", lyrics: [] },
            { song: "The First Time Ever I Saw Your Face", lyrics: [] },
            { song: "Personal Jesus", lyrics: [] },
            { song: "In My Life", lyrics: [] },
            { song: "Sam Hall", lyrics: [] },
            { song: "Danny Boy", lyrics: [] },
            { song: "Desperado (with Don Henley)", lyrics: [] },
            { song: "I'm So Lonesome I Could Cry (duet with Nick Cave)", lyrics: [] },
            { song: "Tear Stained Letter", lyrics: [] },
            { song: "Streets of Laredo", lyrics: [] },
            { song: "We'll Meet Again (with The Whole Cash Gang)", lyrics: [] },
        ],
    },
];

