import joy from './assets/album-joy-division.png';
import kendrick from './assets/album-kendrick-lamar.png';
import miles from './assets/album-miles-davis.png';
import tyler from './assets/album-tyler-creator.png';
import mia from './assets/album-mia.png';
import david from './assets/album-david-bowie.png';
import tame from './assets/album-tame-impala.png';
import johnny from './assets/album-johnny-cash.png';

export const albums = [
    {
        id: 'joy-division',
        idTitle: 'unknown-pleasures',
        name: "Joy Division",
        title: "Unknown Pleasures",
        background: `url(${joy})`,
        year: '1979',
        tracks: '10',
        length: '39:28',
        trackList: [
            "Disorder",
            "Day of the Lords",
            "Candidate",
            "Insight",
            "New Dawn Fades",
            "She's Lost Control",
            "Shadowplay",
            "Wilderness",
            "Interzone",
            "I Remember Nothing",
        ],
    },

    {
        id: 'kendrick-lamar',
        idTitle: 'to-pimp-a-butterfly',
        name: "Kendrick Lamar",
        title: "To Pimp a Butterfly",
        background: `url(${kendrick})`,
        year: '2015',
        tracks: '16',
        length: '78:51',
        trackList: [
            "Wesley's Theory (feat. George Clinton and Thundercat)",
            "For Free? (Interlude)",
            "King Kunta",
            "Institutionalized (feat. Bilal, Anna Wise and Snoop Dogg)",
            "These Walls (feat. Bilal, Anna Wise and Thundercat)",
            "U",
            "Alright",
            "For Sale? (Interlude)",
            "Momma",
            "Hood Politics",
            "How Much a Dollar Cost (feat. James Fauntleroy and Ronald Isley)",
            "Complexion (A Zulu Love) (feat. Rapsody)",
            "The Blacker the Berry",
            "You Ain't Gotta Lie (Momma Said)",
            "I",
            "Mortal Man"
        ],
    },

    {
        id: 'miles-davis',
        idTitle: 'bitches-brew',
        name: "Miles Davis",
        title: "Bitches Brew",
        background: `url(${miles})`,
        year: '1969',
        tracks: '6',
        length: '94:11',
        trackList: [
            "Pharaoh's Dance",
            "Bitches Brew",
            "Spanish Key",
            "John McLaughlin",
            "Miles Runs the Voodoo Down",
            "Sanctuary"
        ],
    },

    {
        id: 'tyler-the-creator',
        idTitle: 'igor',
        name: "Tyler, The Creator",
        title: "Igor",
        background: `url(${tyler})`,
        year: '2019',
        tracks: '12',
        length: '39:43',
        trackList: [
            "Igor's Theme",
            "Earfquake",
            "I think",
            "Exactly what you run from you end up chasing",
            "Running out of time",
            "New magic wand",
            "A boy is a gun*",
            "Puppet",
            "What's good",
            "Gone, gone / Thank you",
            "I don't love you anymore",
            "Are we still friends?"
        ],
    },
    {
        id: 'mia',
        idTitle: 'kala',
        name: "Mia",
        title: "Kala",
        background: `url(${mia})`,
        year: '2007',
        tracks: '12',
        length: '47:32',
        trackList: [
            "Bamboo Banga",
            "Bird Flu",
            "Boyz",
            "Jimmy",
            "Hussel (feat. Afrikan Boy)",
            "Mango Pickle Down River (with The Wilcannia Mob)",
            "20 Dollar",
            "World Town",
            "The Turn",
            "XR2",
            "Paper Planes"
        ],
    },
    {
        id: 'david-bowie',
        idTitle: 'aladdin-sane',
        name: "David Bowie",
        title: "Aladdin Sane",
        background: `url(${david})`,
        year: '1973',
        tracks: '10',
        length: '40:47',
        trackList: [
            "Watch That Man",
            "Aladdin Sane (1913–1938–197?)",
            "Drive-In Saturday",
            "Panic in Detroit",
            "Cracked Actor",
            "Time",
            "The Prettiest Star",
            "Let's Spend the Night Together",
            "The Jean Genie",
            "Lady Grinning Soul",
        ],
    },
    {
        id: 'tame-impala',
        idTitle: 'currents',
        name: "Tame Impala",
        title: "Currents",
        background: `url(${tame})`,
        year: '2015',
        tracks: '13',
        length: '51:12',
        trackList: [
            "Let It Happen",
            "Nangs",
            "The Moment",
            "Yes I'm Changing",
            "Eventually",
            "Gossip",
            "The Less I Know the Better",
            "Past Life",
            "Disciples",
            "'Cause I'm a Man",
            "Reality in Motion",
            "Love/Paranoia",
            "New Person, Same Old Mistakes"
        ],
    },
    {
        id: 'johnny-cash',
        idTitle: 'american-iv-the-man-comes-around',
        name: "Johnny Cash",
        title: "American IV: The Man Comes Around",
        background: `url(${johnny})`,
        year: '2002',
        tracks: '15',
        length: '51:52',
        trackList: [
            "The Man Comes Around",
            "Hurt",
            "Give My Love to Rose",
            "Bridge Over Troubled Water (with Fiona Apple)",
            "I Hung My Head",
            "The First Time Ever I Saw Your Face",
            "Personal Jesus",
            "In My Life",
            "Sam Hall",
            "Danny Boy",
            "Desperado (with Don Henley)",
            "I'm So Lonesome I Could Cry (duet with Nick Cave)",
            "Tear Stained Letter",
            "Streets of Laredo",
            "We'll Meet Again (with The Whole Cash Gang)"
        ],
    },
];

