import { Forfaits } from './forfaits';

export const FORFAITS: Forfaits[] = [
  {
    id: '1',
    ville_destination: 'Cartagène',
    pays_destination: 'Colombie',
    ville_depart: 'Montréal',
    hotel: {
      id: '1',
      nom: 'Hotel Capellán',
      adresse: 'GETSEMANI KR 9 # 29 – 52, Getsemani, 130001 Carthagène des Indes, Colombie',
      etoile: 5,
      nombre_chambre: 50,
      caracteristiques: [
        'À proximité de la plage',
        'À 400m du centre-ville',
        'Accès piscine',
        'Air climatisé',
        'Plateau de courtoisie café/thé',
        'Mini-bar',
        'Bar',
        'Spa',
        'Terrasse sur toit',
        'Accessibilité',
        'Navette aéroport',
        'Stationnement',
      ],
      activites : [
        'Randonnées',
        'Tourisme',
        'Plage',
      ],
    },
    date_depart: '08-02-21',
    date_retour: '15-02-21',
    prix: 1809,
    rabais: 30,
    photo: '../../assets/images/cartagene-colombie.jpg',
    vedette: true,
  },

  {
    id: '2',
    ville_destination: 'Glacis, Île de Mahé',
    pays_destination: 'Iles Seychelles',
    ville_depart: 'Montréal',
    hotel: {
      id: '1',
      nom: 'Bliss Hotel',
      adresse: 'Vista Do Mar, Glacis, Île de Mahé, Seychelles',
      etoile: 4,
      nombre_chambre: 100,
      caracteristiques: [
        'Accès Plage',
        'Vue sur mer',
        'Vue sur jardin',
        'Petit-déjeuner inclus',
        'WiFi gratuit',
        'Climatisation',
        'Plateau de courtoisie café/thé',
        'Mini-bar',
        'Navette aéroport',
      ],
      activites : [
        'Plongée',
        'Yoga',
      ]
    },
    date_depart: '12-12-21',
    date_retour: '20-01-21',
    prix: 1784,
    rabais: 0,
    photo: '../../assets/images/anse-beach-seychelles.jpg',
    vedette: false,
  },

  {
    id: '3',
    ville_destination: 'Zakynthos',
    pays_destination: 'Grèce',
    ville_depart: 'Montréal',
    hotel: {
      id: '1',
      nom: 'Lesante Blu',
      adresse: 'Tragaki, Zakynthos 29100, Grèce',
      etoile: 5,
      nombre_chambre: 100,
      caracteristiques: [
        'Accès plage',
        'Accès piscine',
        'Vue sur mer',
        'WiFi gratuit',
        'Petit-déjeuner inclus',
        'Plateau de courtoisie café/thé',
        'Mini-Bar',
      ],
      activites : [
        'Plongée',
        'Yoga',
      ],
    },
    date_depart: '03-05-21',
    date_retour: '10-05-21',
    prix: 1587.82,
    rabais: 30,
    photo: '../../assets/images/zakynthos-grece.jpg',
    vedette: true,
  },

  {
    id: '4',
    ville_destination: 'Île Belitung',
    pays_destination: 'Indonésie',
    ville_depart: 'Montréal',
    hotel: {
      id: '1',
      nom: 'Eco Beach Tent by Billiton',
      adresse: 'Jl. Tanjung Kelayang Keciput, Sijuk, Tanjung Pandan, Belitung Island 33416 Indonésie',
      etoile: 3,
      nombre_chambre: 100,
      caracteristiques: [
        'Tourisme écologique',
        'Accès plage',
        'Vue sur mer',
        'Petit-déjeuner inclus',
        'Plateau de courtoisie café/thé',
        'Restaurant',
        'Bar',
        'Navette aéroport',
      ],
      activites : [
        'Sports Aquatiques',
        'Randonnées',
      ],
    },
    date_depart: '03-05-21',
    date_retour: '10-05-21',
    prix: 1186,
    rabais: 0,
    photo: '../../assets/images/bangka-belitung-indonesia.jpg',
    vedette: false,
  },

  {
    id: '5',
    ville_destination: 'Mazunte, Oaxaca',
    pays_destination: 'Mexique',
    ville_depart: 'Montréal',
    hotel: {
      id: '1',
      nom: 'Casa Pan de Miel',
      adresse: 'Cerrada del Museo de la Tortuga s/n, Mazunte 70946 Mexique',
      etoile: 3,
      nombre_chambre: 100,
      caracteristiques: [
        'Tourisme écologique',
        'Accès plage',
        'Vue sur mer',
        'Petit-déjeuner inclus',
        'Plateau de courtoisie café/thé',
        'Restaurant',
        'Bar',
        'Navette aéroport',
      ],
      activites : [
        'Sports Aquatiques',
        'Randonnées',
      ],
    },
    date_depart: '03-05-21',
    date_retour: '10-05-21',
    prix: 1186,
    rabais: 0,
    photo: '../../assets/images/mazunte-mexique.jpg',
    vedette: false,
  },

  {
    id: '6',
    ville_destination: 'Bora Bora',
    pays_destination: 'Tahiti',
    ville_depart: 'Montréal',
    hotel: {
      id: '1',
      nom: 'Casa Pan de Miel',
      adresse: 'Cerrada del Museo de la Tortuga s/n, Mazunte 70946 Mexique',
      etoile: 3,
      nombre_chambre: 100,
      caracteristiques: [
        'Tourisme écologique',
        'Accès plage',
        'Vue sur mer',
        'Petit-déjeuner inclus',
        'Plateau de courtoisie café/thé',
        'Restaurant',
        'Bar',
        'Navette aéroport',
      ],
      activites : [
        'Sports Aquatiques',
        'Randonnées',
      ],
    },
    date_depart: '03-05-21',
    date_retour: '10-05-21',
    prix: 1186,
    rabais: 0,
    photo: '../../assets/images/bora-bora-Tahiti.jpg',
    vedette: false,
  },

  {
    id: '7',
    ville_destination: 'Koh Phangan, Suratthani',
    pays_destination: 'Thaïlande',
    ville_depart: 'Montréal',
    hotel: {
      id: '1',
      nom: 'Baan Manali Resort',
      adresse: '210/20 Moo 1 Ao Nai Wok, Koh Phangan, Suratthani 84280 Thailand',
      etoile: 3,
      nombre_chambre: 10,
      caracteristiques: [
        'Accès plage',
        'Accès piscine',
        'Vue sur mer',
        'Petit-déjeuner inclus',
        'Plateau de courtoisie café/thé',
        'Restaurant',
        'Bar',
        'Navette aéroport',
      ],
      activites : [
        'Sports Aquatiques',
        'Randonnées',
      ],
    },
    date_depart: '03-05-21',
    date_retour: '10-05-21',
    prix: 1186,
    rabais: 0,
    photo: '../../assets/images/kho-phangan-thailande.jpg',
    vedette: true,
  },

];
